### PR TITLE
allow index in key props

### PR DESCRIPTION
**Pull request by danmakenoise**
* allow index to be used as the key

When we turned on enforcing jsx-keys, we unknowlingly turned on a warning for using the index as the key. The linter still lets it pass, but it's obnoxious to get a warning in your editor for it.

### CODE REVIEW

**Comment by Roilan** [comment]
💯

**Comment by kesla** [comment]
I think we should do a eslint-ignore when we need to use the index since we should avoid it if possible

**Comment by danmakenoise** [comment]
@kesla this may have been an issue with my local configuration overriding Miclint.

**Comment by danmakenoise** [comment]
Confirmed this was my local config being `airbnb` v14, closing.

**Pull request closed without merging**
