### PR TITLE
Make htmlFor optional for label tags.

### PR DESCRIPTION
**Pull request by ryanscottaudio**
Make htmlFor optional for label tags.

### CODE REVIEW

**Comment by danmakenoise** [comment]
lgtm

**Comment by kesla** [comment]
I don't agree with this. Why are we not enforcing htmlFor? It's good for accessibility and we should probably add it now that we're doing big changes to our frontend stack.

**Comment by danmakenoise** [comment]
@kesla @ellell I think the idea was that since we are porting over "as is" right now, we turned this off until we get everything working. It made the linter fail in places we were not individually working on at the time.

**Comment by danmakenoise** [comment]
@ryanscottaudio correct me if I'm wrong here.

**Comment by ryanscottaudio** [comment]
^ agree with Dan. We don't want to merge things into the `react` branch if tests don't pass, and tests can't pass unless we add `htmlFor` to each `label`, which is changing the functionality of the components and not just translating into React. I also agree that we should implement it after we're done w/ everything else.

**Pull request merged**
