### PR TITLE
lint miclint

### PR DESCRIPTION
**Pull request by kesla**
We weren't actually following miclint in here. So let's lint our linter.

cc @danmakenoise @roilan

### CODE REVIEW

**Comment by Roilan** [comment]
I'd say we stick with `var` because if someone is using a node version that doesn't support it will cause issues.

**Comment by kesla** [comment]
@Roilan I can add this to `v5` if that's a concern.

**Comment by kesla** [comment]
see #51

**Comment by kesla** [comment]
Let's do that - changed the base branch.

**Comment by kesla** [comment]
well actually I'm pretty sure that eslint doesn't work in older nodes - so if you're on node 0.10 or 0.12 you're already in trouble.

**Comment by danmakenoise** [comment]
@kesla @roilan shouldn't be an issue since this linter won't be useful to you if you are in an environment that can't support `const`

**Review by danmakenoise — APPROVED** [review]

**Comment by danmakenoise** [comment]
@kesla we should set the node engine though, so that people get a warning if they try to install in an invalid environment.

**Comment by danmakenoise** [comment]
@roilan would restricting it to the node versions help solve this in your eyes?

**Comment by Roilan** [comment]
@kesla @danmakenoise I'd say we add the node version warning. I've seen a couple modules default to const and becomes a debugging nightmare.

**Comment by orrybaram** [comment]
Can we start a changelog for miclint? Seems like we're constantly changing stuff and I feel like people (me) are out of the loop unless they;re actively checking in on all the PRs

**Comment by kesla** [comment]
@Roilan was that any time recently?

node 0.10 & 0.12 have been unsupported for months at this point. Node 0.10 reached EOL at 2016-10-31 while node 0.12 reached EOL at 2016-12-31.

So at this point none of the supported node version will have any problems w using `const`.

I can def add the engines field, but what I'm also trying to figure out is if `I've seen a couple modules default to const and becomes a debugging nightmare.` is something that belongs to the past or if it is still a problem.

**Comment by kesla** [comment]
@orrybaram sure, I'll add a changelog to #51

**Comment by orrybaram** [comment]
@kesla thanks! 😁

**Pull request merged**
